upstream backend {
    server 127.0.0.1:8080;

    keepalive 64;
}

server {
    if ($host = api-staging.joinhello.app) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name api-staging.joinhello.app;
    location / {
        return 301 https://$host$request_uri;
    }


}
server {
    listen 443 ssl;
    server_name api-staging.joinhello.app;
    ssl_certificate /etc/letsencrypt/live/api-staging.joinhello.app/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/api-staging.joinhello.app/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    access_log /var/log/nginx/staging.access.log;

    client_header_buffer_size 1m;
    large_client_header_buffers 4 1m;

    client_header_timeout 300s;

    location / {
        client_max_body_size 5G;
        client_body_buffer_size 1m;

        client_body_timeout 300s;

        keepalive_timeout 300s;
        send_timeout 300s;

        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
        proxy_max_temp_file_size 0;
        proxy_read_timeout 300s;

        proxy_pass http://backend;
    }

}