# Use the official Node.js 16 image as a parent image
FROM node:18-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN yarn

# Copy the rest of your application's code
COPY . .

# Build your TypeScript files
RUN yarn version

# Expose the port the app runs on
EXPOSE 3000

# Command to run your app
CMD ["yarn", "start"]
