# Use the official Node.js 16 image as a parent image
FROM node:20-alpine

# Install PostgreSQL client
RUN apk update && apk add --no-cache postgresql-client

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN yarn install
RUN yarn global add nodemon ts-node typescript

# Copy the rest of your application's code
COPY . .


# Expose the port the app runs on
EXPOSE 3000

# Command to run your app
CMD ["yarn", "start"]

